---
- name: Validate Docker Compose configuration
  command: docker compose config
  args:
    chdir: "{{ app_dir }}"
  changed_when: false

- name: Start MLOps platform
  command: docker compose up -d --build
  args:
    chdir: "{{ app_dir }}"

- name: Read Docker Compose status
  command: docker compose ps
  args:
    chdir: "{{ app_dir }}"
  register: compose_status
  changed_when: false

- name: Display Docker Compose status
  debug:
    var: compose_status.stdout_lines
